import { execSync } from 'node:child_process'
import { chmodSync, existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import path from 'node:path'
import { log } from './log.js'

const LOCAL_DIR = path.join(homedir(), 'Library/Application Support/Local')

const EXPECTED_PLUGINS = ['elementor', 'mcp-adapter', 'emcp-tools', 'plugin-check']

function expand(p) {
  return p.startsWith('~') ? path.join(homedir(), p.slice(1)) : p
}

/** Match the Local site whose path contains the DEV_TARGET. */
function resolveSite(devTarget) {
  const registry = path.join(LOCAL_DIR, 'sites.json')
  if (!existsSync(registry)) {
    throw new Error(`Local's site registry not found at ${registry} — is LocalWP installed?`)
  }
  const sites = Object.values(JSON.parse(readFileSync(registry, 'utf8')))
  if (!devTarget) {
    throw new Error('Set DEV_TARGET in .env to a Local site path so doctor can identify the site')
  }
  const site = sites.find((s) => devTarget.startsWith(`${expand(s.path)}${path.sep}`))
  if (!site) {
    throw new Error(`No Local site contains DEV_TARGET (${devTarget})`)
  }
  return site
}

function resolvePhpBinary(site) {
  const version = site.services?.php?.version
  if (!version) {
    throw new Error(`Local site "${site.name}" has no php service in the registry`)
  }
  const servicesDir = path.join(LOCAL_DIR, 'lightning-services')
  const match = readdirSync(servicesDir).find((d) => d.startsWith(`php-${version}`))
  if (!match) {
    throw new Error(`No lightning-services dir for php-${version} under ${servicesDir}`)
  }
  return path.join(servicesDir, match, 'bin/darwin/bin/php')
}

export function doctor(ctx) {
  const problems = []
  const site = resolveSite(ctx.paths.devTarget)
  const sitePublic = path.join(expand(site.path), 'app/public')
  const phpBinary = resolvePhpBinary(site)
  const socket = path.join(LOCAL_DIR, 'run', site.id, 'mysql/mysqld.sock')
  const wp = execSync('which wp', { encoding: 'utf8' }).trim()

  if (!existsSync(phpBinary)) problems.push(`PHP binary missing: ${phpBinary}`)
  if (!existsSync(socket)) {
    problems.push(`MySQL socket missing (site not running in Local?): ${socket}`)
  }

  // Dev-site equipment: what the shared multi-plugin site is expected to carry.
  const pluginsDir = path.join(sitePublic, 'wp-content/plugins')
  for (const slug of EXPECTED_PLUGINS) {
    if (!existsSync(path.join(pluginsDir, slug))) {
      problems.push(`Dev site is missing plugin: ${slug}`)
    }
  }

  // MCP servers: EMCP's Elementor tools ride mcp-adapter under this fixed id;
  // the repo's own server only exists if its PHP registers one.
  const servers = {}
  const wpCliBase = [
    phpBinary,
    `-d mysqli.default_socket=${socket}`,
    wp,
    `--path=${sitePublic}`
  ]
  if (existsSync(path.join(pluginsDir, 'emcp-tools'))) {
    servers.emcp = {
      command: phpBinary,
      args: [
        `-d`, `mysqli.default_socket=${socket}`,
        wp,
        `--path=${sitePublic}`,
        'mcp-adapter', 'serve', '--server=emcp-tools-server', '--user=admin'
      ]
    }
  }
  let registersOwnServer = false
  try {
    registersOwnServer =
      execSync(`grep -rl "mcp_adapter_init" ${JSON.stringify(ctx.paths.php)} | head -1`, {
        encoding: 'utf8'
      }).trim() !== ''
  } catch {
    // no match — grep exits 1
  }
  if (registersOwnServer) {
    servers[ctx.config.slug] = {
      command: phpBinary,
      args: [
        `-d`, `mysqli.default_socket=${socket}`,
        wp,
        `--path=${sitePublic}`,
        'mcp-adapter', 'serve', `--server=${ctx.config.slug}`, '--user=admin'
      ]
    }
  }

  writeFileSync(
    path.join(ctx.root, '.mcp.json'),
    `${JSON.stringify({ mcpServers: servers }, null, 2)}\n`
  )
  log.success(`.mcp.json written (${Object.keys(servers).join(', ') || 'no servers'})`)

  // wp wrapper: machine-specific (absolute paths), lives gitignored in dev/.
  mkdirSync(path.join(ctx.root, 'dev'), { recursive: true })
  const wrapper = path.join(ctx.root, 'dev/wp')
  writeFileSync(
    wrapper,
    `#!/usr/bin/env bash\n# Generated by \`arts-wp doctor\` — wp-cli against the ${site.name} Local site.\nexec ${JSON.stringify(phpBinary)} -d mysqli.default_socket=${JSON.stringify(socket)} ${JSON.stringify(wp)} --path=${JSON.stringify(sitePublic)} "$@"\n`
  )
  chmodSync(wrapper, 0o755)
  log.success(`wp wrapper written: dev/wp (site: ${site.name}, php ${site.services.php.version})`)
  void wpCliBase

  if (problems.length > 0) {
    log.warn(`Doctor found ${problems.length} issue(s):`)
    for (const p of problems) log.warn(`  - ${p}`)
  } else {
    log.success('Dev site equipment check: all present')
  }
  return problems
}
